load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

#mediapipe_aar(
    #name = "mediapipe_face_detection",
    #calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
#)

mediapipe_aar(
    name = "mediapipe_hand_tracking",
    calculators = ["//mediapipe/graphs/hand_tracking:mobile_calculators"],
)
